---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    name: demo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:      demo
  namespace: demo
spec:
  storageClassName: nfs-delete
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 50M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:      demo
  namespace: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
      volumes:
      - name: volume100
        persistentVolumeClaim:
          claimName: demo
---
apiVersion: v1
kind: Service
metadata:
  name:      demo
  namespace: demo
  labels:
    app: demo
spec:
  type: ClusterIP
  selector:
    app: demo
  ports:
    - name:       http
      protocol:   TCP
      port:       80
      targetPort: 80
    - name:       https
      protocol:   TCP
      port:       443
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  namespace: demo
  labels:
    app: demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - demo.doshoru.com
    secretName: wildcard.dev.doshoru.com
  rules:
  - host: demo.dev.doshoru.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: demo
              port:
                number: 80
        - path: /
          pathType: Prefix
          backend:
            service:
              name: demo
              port:
                number: 443
  ingressClassName: nginx
